# This GitHub Action provides simple CI process. Install dependencies -> Build -> Run tests

name: Space Rockets Challenge CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build
      run: yarn build
    - name: Unit tests
      run: yarn test
