# This GitHub Action provides simple CI process. Install dependencies -> Build -> Run tests

name: Challenge CI - Unit tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up NodeJS v12
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build
      run: yarn build
    - name: Unit tests
      run: yarn test
